/**
 * Triggered by "On form submit" to sync specific data across sheets.
 * Handles multiple simultaneous submissions safely.
 */



function syncOnFormSubmit(e) {
  // 1. Get the row number from the form submission event
  const submittedRow = e ? e.range.getRow() : null;
  
  // Safety: If it's Row 1, stop immediately.
  if (!submittedRow || submittedRow === 1) {
    console.log("No valid data row detected.");
    return;
  }

  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sourceSheet = ss.getSheetByName("Cleaned Data");
  const targetSheet = ss.getSheetByName("Complaint Scheduling");
  
  let rowData;
  let isRowComplete = false;
  
  // --- EXTENDED WAIT SETTINGS (5 MINUTES) ---
  const maxAttempts = 30;      // 30 attempts
  const sleepTime = 16000;     // 10 seconds each = 300 seconds total
  
  for (let attempts = 0; attempts < maxAttempts; attempts++) {
    SpreadsheetApp.flush(); 
    
    // Get columns A through M for the specific row that was submitted
    rowData = sourceSheet.getRange(submittedRow, 1, 1, 13).getValues()[0];
    
    // CRITICAL CHECK: 
    // We check if Column B (Complaint ID) has been generated by your formulas.
    // If Column B is empty, or if it says "Complaint ID" (the header), we wait.
    const complaintId = rowData[1];
    
    if (complaintId && complaintId !== "" && complaintId !== "Complaint ID") {
      isRowComplete = true;
      console.log(`Success! Data found for ID: ${complaintId} at attempt ${attempts + 1}`);
      break; 
    }
    
    console.log(`Waiting for formulas in 'Cleaned Data' row ${submittedRow}... Attempt ${attempts + 1}`);
    Utilities.sleep(sleepTime); 
  }

  // --- EXECUTION ---
  if (isRowComplete) {
    // Formatting the customer name
    const company = rowData[2] || "";
    const client = rowData[3] || "";
    const fullCustomer = (company && client) ? `${company} / ${client}` : (company || client);
    
    const finalRow = [
      rowData[0],    // A: Time Stamp
      rowData[1],    // B: Complaint ID
      fullCustomer,  // C: Customer Name
      "",            // D: Assigned To
      rowData[6],    // E: Complaint / Issue
      rowData[8],    // F: Address
      rowData[12],   // G: Contact Person Number
      rowData[4],    // H: Service Type
      rowData[10],   // I: Machine / System Type
      "",            // J: Service Report type
      ""             // K: Remark / Status
    ];
    
    const lock = LockService.getScriptLock();
    try {
      lock.waitLock(30000); 
      
      // Insert at Row 2
      targetSheet.insertRowAfter(1);
      const newRange = targetSheet.getRange(2, 1, 1, finalRow.length);
      newRange.setValues([finalRow]);
      
      // Clean up formatting so it doesn't look like a header (removes bold/background)
      newRange.setFontWeight("normal")
              .setBackground(null)
              .setFontColor("black");

      // Auto-sort: Newest Timestamp (Col A) at the top
      const lastRow = targetSheet.getLastRow();
      if (lastRow > 1) {
        targetSheet.getRange(2, 1, lastRow - 1, 11).sort({column: 1, ascending: false});
      }
      
      lock.releaseLock();
    } catch (err) {
      console.log("Error: " + err);
    }
  } else {
    console.log("Timed out: Data never appeared in 'Cleaned Data' for row " + submittedRow);
  }
}



function onEdit(e) {
  const range = e.range;
  const sheet = range.getSheet();
  const sheetName = sheet.getName();
  
  // 1. SETTINGS: Change these to match your exact sheet names
  const schedulingSheetName = "Complaint Scheduling"; 
  const intakeSheetName = "BPMS - Complaint Intake & Dispatch";
  const assignedToCol = 4; // Column D (Assigned To)
  const complaintIdCol = 2; // Column B (Complaint ID)
  const targetTechCol = 11; // Column K (Technician Name in Intake Sheet)

  // 2. CHECK: Only run if we are on the Scheduling sheet and editing the "Assigned To" column
  if (sheetName === schedulingSheetName && range.getColumn() === assignedToCol && range.getRow() > 1) {
    
    const row = range.getRow();
    const complaintId = sheet.getRange(row, complaintIdCol).getValue();
    const technicianName = range.getValue();
    
    if (!complaintId) return; // Exit if there is no ID to match

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const intakeSheet = ss.getSheetByName(intakeSheetName);
    
    if (!intakeSheet) {
      console.log("Error: Target sheet not found.");
      return;
    }

    // 3. FIND & UPDATE: Look for the Complaint ID in the Intake sheet
    const intakeData = intakeSheet.getDataRange().getValues();
    let found = false;

    for (let i = 0; i < intakeData.length; i++) {
      // intakeData[i][1] is Column B (Complaint ID) in the Intake Sheet
      if (intakeData[i][1] == complaintId) {
        // Set the value in Column K (Index 10)
        intakeSheet.getRange(i + 1, targetTechCol).setValue(technicianName);
        found = true;
        break; 
      }
    }

    if (found) {
      console.log("Updated technician for ID: " + complaintId);
    } else {
      console.log("Complaint ID not found in Intake sheet.");
    }
  }
}
